services:

  db:
    image: mysql:latest
    container_name: database_my
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastapi_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
        - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: fastapi-web
    ports:
        - "8000:8000"
    depends_on:
      db:
        condition: service_healthy     
    
    environment:
      - sql_database_url=mysql+pymysql://root:1234@db/fastapi_db
        
volumes:
  mysql_data: